version: '3.7'

services:
  mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      -
    entrypoint: /bin/bash ./entrypoint.sh